#!/usr/bin/env bash


# Define server host and SSH key file
server="18.204.7.135"
ssh_key="~/.ssh/school"

# Use SSH to connect to the server with the specified key and user
ssh -i "~/.ssh/school "ubuntu@18.204.7.135"
