#!/usr/bin/evn bash
# SSH client configuration

Host *
    passwordAuthentication no
    Identityfile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHost yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
